### ISSUE TITLE
npm version not the same as github verison

### ISSUE THREAD

**Issue by peckomingo** [yeoman/generator-gulp-webapp#278]
Here on github you mentioned that you are using BrowserSync and libsass but on npm there is still livereload. So it seems npm is not up to date?

**Comment by arthurvr** [comment]
NPM has [the latest version](https://github.com/yeoman/generator-gulp-webapp/releases), the github repo has the newest stuff (`master`). The next version will have libsass and browsersync.

**Comment by sindresorhus** [comment]
https://github.com/yeoman/generator-gulp-webapp/issues/279
