### ISSUE TITLE
Jekyll Recipe

### ISSUE THREAD

**Issue by rizqinizamil** [yeoman/generator-gulp-webapp#364]
Would you mind to create Jekyll recipe?
I have tried other Jekyll generator but I think it will be great if there is Jekyll recipe for gulp-webapp.

Thanks.

**Comment by arthurvr** [comment]
For gulp-webapp to be made Jekyll compatible there are quite a few things that would need to happen. I personally believe this is a way better fit for a separate generator as the recipe would be complicated and maybe difficult to maintain.

 
> I have tried other Jekyll generator but I think it will be great if there is Jekyll recipe for gulp-webapp.

Why? What was wrong with the jekyll generator and why wouldn't you just improve that generator?

**Comment by rizqinizamil** [comment]
@arthurvr I see. I think I will try to improve jekyll generator If this repo owner say so :)

**Comment by silvenon** [comment]
Especially because this generator is meant for webapps. Jekyll is more suited for blogs and simple sites like that.
